#!/usr/bin/env python3
import subprocess
import time
import requests
import re
from typing import Dict, List
import os

def parse_ysp_file(file_path: str) -> List[Dict[str, str]]:
    """解析 ysp.txt 文件，提取频道信息"""
    channels = []
    
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    for line in lines:
        line = line.strip()
        # 跳过空行和分类标题
        if not line or '#genre#' in line:
            continue
        
        # 解析频道名称和URL
        if ',' in line:
            parts = line.split(',', 1)
            if len(parts) == 2:
                channel_name = parts[0].strip()
                url = parts[1].strip()
                
                # 从URL中提取参数
                params_match = re.search(r'cnlid=(\d+)&livepid=(\d+)&defn=(\w+)', url)
                if params_match:
                    channels.append({
                        'name': channel_name,
                        'cnlid': params_match.group(1),
                        'livepid': params_match.group(2),
                        'defn': params_match.group(3)
                    })
    
    return channels

def get_stream_url(cnlid: str, livepid: str, defn: str = "fhd", retries: int = 3) -> str:
    """通过本地 FastAPI 服务获取直播流地址"""
    for attempt in range(retries):
        try:
            # 调用本地运行的 FastAPI 服务
            url = f"http://127.0.0.1:8080/ysp?cnlid={cnlid}&livepid={livepid}&defn={defn}"
            response = requests.get(url, timeout=10)
            
            if response.status_code == 200:
                if response.headers.get('content-type', '').startswith('application/json'):
                    # 如果是JSON响应，返回错误
                    data = response.json()
                    return f"# ERROR: {data.get('error', 'Unknown error')}"
                else:
                    # 获取重定向后的最终URL
                    return response.url
        except requests.RequestException as e:
            print(f"请求失败 (尝试 {attempt + 1}/{retries}): {e}")
            time.sleep(1)
    
    return "# ERROR: Failed to get stream URL"

def generate_m3u(channels: List[Dict[str, str]], output_file: str = "live.m3u"):
    """生成 M3U 文件"""
    with open(output_file, 'w', encoding='utf-8') as f:
        # 写入 M3U 头部
        f.write("#EXTM3U\n")
        f.write("#EXT-X-VERSION:3\n")
        f.write("#EXT-X-INDEPENDENT-SEGMENTS\n")
        f.write("#EXT-X-TARGETDURATION:5\n")
        f.write("# Generated by YSP Stream Generator\n")
        
        # 按分类分组处理
        current_group = None
        
        for channel in channels:
            # 跳过VIP频道（可选）
            if 'VIP' in channel['name']:
                continue
            
            print(f"处理频道: {channel['name']}")
            
            # 获取直播流地址
            stream_url = get_stream_url(channel['cnlid'], channel['livepid'], channel['defn'])
            
            if stream_url.startswith("# ERROR"):
                # 记录错误但继续处理其他频道
                f.write(f"# {channel['name']}: {stream_url}\n")
                continue
            
            # 写入频道信息到 M3U
            f.write(f"#EXTINF:-1 tvg-id=\"\" tvg-name=\"{channel['name']}\" tvg-logo=\"\" group-title=\"Live\",{channel['name']}\n")
            f.write(f"{stream_url}\n")
    
    print(f"M3U 文件已生成: {output_file}")

def main():
    import sys
    
    # 设置当前目录
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    # 检查 ysp.txt 文件是否存在
    if not os.path.exists("ysp.txt"):
        print("错误: ysp.txt 文件不存在")
        sys.exit(1)
    
    # 解析频道信息
    print("正在解析 ysp.txt...")
    channels = parse_ysp_file("ysp.txt")
    print(f"找到 {len(channels)} 个频道")
    
    # 启动 FastAPI 服务
    print("启动 FastAPI 服务...")
    process = subprocess.Popen(
        ["python", "yspapp.py"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    
    try:
        # 等待服务启动
        print("等待服务启动...")
        time.sleep(5)
        
        # 测试服务是否正常
        test_response = requests.get("http://127.0.0.1:8080/ysp?cnlid=2024078201&livepid=600001859&defn=fhd", timeout=5)
        if test_response.status_code != 200:
            print("服务启动失败")
            return
        
        print("服务已启动，开始获取流地址...")
        
        # 生成 M3U 文件
        generate_m3u(channels, "live.m3u")
        
        # 生成简化版 M3U（只包含成功获取的频道）
        print("\n处理完成！")
        
    except Exception as e:
        print(f"处理过程中出错: {e}")
    finally:
        # 停止服务
        print("停止 FastAPI 服务...")
        process.terminate()
        process.wait()

if __name__ == "__main__":
    main()
