# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tvlist.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tvlist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctvlist.proto\"A\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x1a\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0c.DataWrapper\x12\x0b\n\x03msg\x18\x03 \x01(\t\"9\n\x0b\x44\x61taWrapper\x12\x0f\n\x07page_id\x18\x01 \x01(\t\x12\x19\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x08.Content\"U\n\x07\x43ontent\x12\x11\n\tmodule_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\tlist_name\x18\r \x01(\t\x12\x16\n\x04list\x18\x0f \x03(\x0b\x32\x08.Channel\"\xa4\x02\n\x07\x43hannel\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07livepid\x18\x04 \x01(\t\x12\x0c\n\x04logo\x18\x05 \x01(\t\x12\r\n\x05\x63nlid\x18\x06 \x01(\t\x12\x0e\n\x06is_pay\x18\x07 \x01(\t\x12\r\n\x05is_4k\x18\x08 \x01(\t\x12\x0f\n\x07has_epg\x18\t \x01(\t\x12\r\n\x05\x64\x61tes\x18\n \x03(\t\x12\x0e\n\x06source\x18\x0b \x01(\t\x12\r\n\x05icon1\x18\x0c \x01(\t\x12\r\n\x05icon2\x18\r \x01(\t\x12\x10\n\x08\x66ield_14\x18\x0e \x01(\t\x12\x10\n\x08\x66ield_15\x18\x0f \x01(\x0c\x12\x1a\n\x08pay_info\x18\x10 \x01(\x0b\x32\x08.PayInfo\x12\x10\n\x08\x66ield_17\x18\x11 \x01(\t\x12\x10\n\x08\x66ield_18\x18\x12 \x01(\x05\"%\n\x07PayInfo\x12\x1a\n\x06\x64\x65tail\x18\x01 \x01(\x0b\x32\n.PayDetail\"/\n\tPayDetail\x12\x10\n\x08pay_type\x18\x01 \x01(\t\x12\x10\n\x08pay_desc\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tvlist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE']._serialized_start=16
  _globals['_RESPONSE']._serialized_end=81
  _globals['_DATAWRAPPER']._serialized_start=83
  _globals['_DATAWRAPPER']._serialized_end=140
  _globals['_CONTENT']._serialized_start=142
  _globals['_CONTENT']._serialized_end=227
  _globals['_CHANNEL']._serialized_start=230
  _globals['_CHANNEL']._serialized_end=522
  _globals['_PAYINFO']._serialized_start=524
  _globals['_PAYINFO']._serialized_end=561
  _globals['_PAYDETAIL']._serialized_start=563
  _globals['_PAYDETAIL']._serialized_end=610
# @@protoc_insertion_point(module_scope)
